site_name: GenAI Music Lab Docs

theme:
  name: "material" #readthedocs
  icon:
    repo: simple/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate

markdown_extensions:
  # Include admonitions https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - footnotes
  - toc:
      permalink: true
      title: On this page
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - mkdocstrings
  - mermaid2
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# Custom admonitions
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - API Reference: api-reference.md
  - Explanation: explanation.md